version: '3.7'
services:
  comunion-redis:
    image: redis
    container_name: comunion-redis
    restart: always
    ports:
      - 6379:6379
  comunion-mysql:
    image: mysql:5.7
    container_name: comunion-mysql
    restart: always
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=Comunion2021
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - 9000:9000
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server /data